'use strict';
// On-demand local narration of saved article snapshots. One GPU/CPU request at a time.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const DIR=path.join(process.env.LATERAL_DATA_DIR||'/data','article-audio');
const BASE=(process.env.LATERAL_TTS_URL||'http://chatterbox-tts:8880').replace(/\/$/,'');
const VOICE=process.env.LATERAL_TTS_VOICE||'HermesVoice',VERSION='hermes-article-v1';
const jobs=new Map(),queue=[];let running=false;
const read=f=>{try{return JSON.parse(fs.readFileSync(f,'utf8'));}catch{return null;}};
const hash=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,32);
const safe=id=>/^[a-f0-9]{32}$/.test(id||'');
function speechText(doc){return [doc.title,doc.byline?'By '+doc.byline:'',doc.text].filter(Boolean).join('\n\n').replace(/```[\s\S]*?```/g,' ').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^\s*#{1,6}\s+/gm,'').replace(/[*_`]/g,'').replace(/\s+/g,' ').trim();}
function chunks(text,max=380){const words=text.split(/\s+/),out=[];let s='';for(const word of words){if(word.length>max){if(s){out.push(s);s='';}for(let i=0;i<word.length;i+=max)out.push(word.slice(i,i+max));}else if(s.length+word.length+1>max){out.push(s);s=word;}else s+=(s?' ':'')+word;}if(s)out.push(s);return out;}
function descriptor(doc,voice=VOICE){if(!doc?.text)throw Object.assign(new Error('No readable saved article.'),{status:404});if(![VOICE,'HermesVoice','SamaraNew'].includes(voice))throw Object.assign(new Error('Choose an available local voice.'),{status:400});const text=speechText(doc);return {id:hash(VERSION+'\0'+voice+'\0'+text),key:doc.key,voice,text};}
const folder=id=>path.join(DIR,id),file=id=>path.join(folder(id),'narration.wav');
function manifest(j){const {controller,text,...meta}=j;fs.mkdirSync(folder(j.id),{recursive:true});const f=path.join(folder(j.id),'status.json');fs.writeFileSync(f+'.tmp',JSON.stringify(meta));fs.renameSync(f+'.tmp',f);}
function status(doc,voice=VOICE){const d=descriptor(doc,voice),memory=jobs.get(d.id),stored=read(path.join(folder(d.id),'status.json'));let s=memory||stored||{...d,state:'none',done:0,total:chunks(d.text).length};if(s.state==='ready'&&!fs.existsSync(file(d.id)))s={...s,state:'none'};if(!memory&&['queued','generating'].includes(s.state))s={...s,state:'interrupted',error:'Generation was interrupted. Retry to continue from saved sections.'};return {id:d.id,key:d.key,voice:d.voice,state:s.state,done:s.done||0,total:s.total||0,error:s.error||'',duration:s.duration||0,audioURL:s.state==='ready'?'/api/lateral/article-audio/file?id='+d.id:'',generatedAt:s.generatedAt||''};}
// Soundfile emits PCM WAV; parse RIFF chunks rather than assuming a 44-byte input header.
function wave(buf){if(buf.length<44||buf.toString('ascii',0,4)!=='RIFF'||buf.toString('ascii',8,12)!=='WAVE')throw new Error('The voice service returned invalid audio.');let fmt,data;for(let i=12;i+8<=buf.length;){const n=buf.readUInt32LE(i+4),end=i+8+n;if(end>buf.length)throw new Error('Incomplete audio from the voice service.');const tag=buf.toString('ascii',i,i+4);if(tag==='fmt ')fmt=buf.subarray(i+8,end);if(tag==='data')data=buf.subarray(i+8,end);i=end+(n%2);}if(!fmt||fmt.length<16||!data?.length||fmt.readUInt16LE(0)!==1||fmt.readUInt16LE(14)!==16)throw new Error('Expected 16-bit PCM narration from the voice service.');return {fmt,data,rate:fmt.readUInt32LE(4),align:fmt.readUInt16LE(12)};}
function joinWaves(parts){const first=wave(parts[0]),pcm=[];for(let i=0;i<parts.length;i++){const w=wave(parts[i]);if(!w.fmt.subarray(0,16).equals(first.fmt.subarray(0,16)))throw new Error('Voice service changed audio format between sections.');if(i)pcm.push(Buffer.alloc(Math.round(first.rate*.16)*first.align));pcm.push(w.data);}const data=Buffer.concat(pcm),header=Buffer.alloc(44);header.write('RIFF');header.writeUInt32LE(data.length+36,4);header.write('WAVEfmt ',8);header.writeUInt32LE(16,16);first.fmt.copy(header,20,0,16);header.write('data',36);header.writeUInt32LE(data.length,40);return {buffer:Buffer.concat([header,data]),duration:data.length/(first.rate*first.align)};}
async function synth(text,voice,signal){const r=await fetch(BASE+'/v1/audio/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:text,voice,response_format:'wav'}),signal:AbortSignal.any([signal,AbortSignal.timeout(12*60000)])});if(!r.ok)throw new Error(r.status===404?'The selected voice was not found in Chatterbox.':'Chatterbox could not generate audio (HTTP '+r.status+').');const buf=Buffer.from(await r.arrayBuffer());if(buf.length>40*1024*1024)throw new Error('The voice service returned an oversized section.');wave(buf);return buf;}
async function pump(){if(running)return;running=true;try{while(queue.length){const j=queue.shift();if(j.state==='cancelled'){jobs.delete(j.id);if(j.deleted)fs.rmSync(folder(j.id),{recursive:true,force:true});continue;}j.controller=new AbortController();try{j.state='generating';manifest(j);const sections=chunks(j.text),parts=[];for(let i=0;i<sections.length;i++){if(j.cancelRequested||j.controller.signal.aborted)throw new Error('Cancelled');const f=path.join(folder(j.id),i+'.wav');let buf=fs.existsSync(f)?fs.readFileSync(f):null;if(buf){try{wave(buf);}catch{buf=null;}}if(!buf){buf=await synth(sections[i],j.voice,j.controller.signal);if(j.cancelRequested||j.controller.signal.aborted)throw new Error('Cancelled');fs.writeFileSync(f+'.tmp',buf);fs.renameSync(f+'.tmp',f);}parts.push(buf);if(parts.reduce((n,b)=>n+b.length,0)>256*1024*1024)throw new Error('This narration exceeds the 256 MB audio limit.');j.done=i+1;manifest(j);}const joined=joinWaves(parts);fs.writeFileSync(file(j.id)+'.tmp',joined.buffer);fs.renameSync(file(j.id)+'.tmp',file(j.id));j.state='ready';j.duration=joined.duration;j.generatedAt=new Date().toISOString();j.error='';// Completed files no longer need separate chunk copies.
for(let i=0;i<sections.length;i++){try{fs.unlinkSync(path.join(folder(j.id),i+'.wav'));}catch{}}
}catch(e){j.state=(j.cancelRequested||j.controller.signal.aborted)?'cancelled':'error';j.error=j.state==='cancelled'?'Generation cancelled.':e.name==='TimeoutError'?'Chatterbox took too long. Retry to resume saved sections.':e.message||'Could not generate narration.';}finally{if(j.deleted)fs.rmSync(folder(j.id),{recursive:true,force:true});else manifest(j);delete j.controller;delete j.text;jobs.delete(j.id);}}}finally{running=false;}}
function start(doc,voice=VOICE){const d=descriptor(doc,voice),s=status(doc,voice);if(['queued','generating','ready'].includes(s.state))return s;if(d.text.length>60000)throw Object.assign(new Error('This article is too long for local narration (60,000 characters). Browser read-aloud is available below.'),{status:400});if(queue.length>=8)throw Object.assign(new Error('The narration queue is full. Try again after another article finishes.'),{status:429});const j={...d,state:'queued',done:0,total:chunks(d.text).length,error:''};jobs.set(j.id,j);queue.push(j);manifest(j);setImmediate(()=>pump());return status(doc,voice);}
function cancel(doc,voice=VOICE){const d=descriptor(doc,voice),j=jobs.get(d.id);if(j){j.state='cancelled';j.cancelRequested=true;manifest(j);}return status(doc,voice);}
function forget(key){if(!fs.existsSync(DIR))return;for(const id of fs.readdirSync(DIR)){if(!safe(id))continue;const m=read(path.join(folder(id),'status.json'));if(m?.key!==key)continue;const j=jobs.get(id);if(j){j.state='cancelled';j.cancelRequested=true;j.deleted=true;}else fs.rmSync(folder(id),{recursive:true,force:true});}}
function pickLibrary(items,stories,now=Date.now()){const active=new Set(stories.filter(s=>s.status!=='buried').map(s=>s.id)),day=Math.floor(now/86400000),ranked=items.slice(0,500).map(m=>{const related=(m.storyIds||[]).some(id=>active.has(id)),doc=require('./archive').get(m.key);let audio=null;try{if(doc)audio=status(doc);}catch{}return {...m,audio:audio||{state:'none'},reason:related?'Saved for a story you’re following':'A saved piece to return to',related,tie:hash(day+':'+m.key)};}).sort((a,b)=>Number(b.related)-Number(a.related)||Number(b.audio.state==='ready')-Number(a.audio.state==='ready')||a.tie.localeCompare(b.tie));const selected=[],sites=new Set();for(const m of ranked){if(sites.has(m.site||m.url)&&selected.length<2)continue;selected.push(m);sites.add(m.site||m.url);if(selected.length===3)break;}for(const m of ranked)if(selected.length<3&&!selected.some(x=>x.key===m.key))selected.push(m);return selected.map(({key,title,site,words,url,reason,audio})=>({key,title,site,words,url,reason,audio}));}
function serve(req,res,id){if(!safe(id)){res.writeHead(404);res.end();return;}const m=read(path.join(folder(id),'status.json')),archive=require('./archive');if(m?.state!=='ready'||!archive.get(m.key)||!fs.existsSync(file(id))){res.writeHead(404);res.end();return;}const n=fs.statSync(file(id)).size;let start=0,end=n-1,status=200;const range=req.headers.range;if(range){const match=/^bytes=(\d*)-(\d*)$/.exec(range);if(!match||(!match[1]&&!match[2])){res.writeHead(416,{'Content-Range':'bytes */'+n});res.end();return;}if(!match[1])start=Math.max(0,n-Number(match[2]));else {start=Number(match[1]);if(match[2])end=Math.min(end,Number(match[2]));}if(start>end||start>=n||!Number.isSafeInteger(start)||!Number.isSafeInteger(end)){res.writeHead(416,{'Content-Range':'bytes */'+n});res.end();return;}status=206;}res.writeHead(status,{'Content-Type':'audio/wav','Content-Length':end-start+1,'Accept-Ranges':'bytes','Cache-Control':'private, no-cache','Content-Disposition':'inline; filename="lateral-'+id+'.wav"',...(status===206?{'Content-Range':`bytes ${start}-${end}/${n}`}:{})});if(req.method==='HEAD'){res.end();return;}const stream=fs.createReadStream(file(id),{start,end});stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());stream.pipe(res);}
async function route(req,url,res,send){const p=url.pathname.replace(/^\/api\/lateral/,'');if(!p.startsWith('/article-audio/'))return false;res.setHeader('Cache-Control','no-store');const sub=p.slice(15);try{if(sub==='file'&&['GET','HEAD'].includes(req.method)){serve(req,res,url.searchParams.get('id'));return true;}if(sub==='voices'&&req.method==='GET'){try{const r=await fetch(BASE+'/v1/audio/voices',{signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error();const d=await r.json();return send(res,200,{available:true,defaultVoice:VOICE,voices:(d.data||[]).filter(v=>[VOICE,'HermesVoice','SamaraNew'].includes(v.id)),local:true});}catch{return send(res,200,{available:false,defaultVoice:VOICE,voices:[],error:'Chatterbox is unavailable. Browser read-aloud still works.'});}}let body={};if(req.method==='POST'){let raw='';for await(const c of req){raw+=c;if(raw.length>4096)return send(res,413,{error:'Request too large.'});}try{body=JSON.parse(raw);}catch{return send(res,400,{error:'Invalid request.'});}}const key=body.key||url.searchParams.get('key'),voice=body.voice||url.searchParams.get('voice')||VOICE,doc=require('./archive').get(key);if(!doc)return send(res,404,{error:'No saved copy of that article.'});if(sub==='status'&&req.method==='GET')return send(res,200,status(doc,voice));if(sub==='generate'&&req.method==='POST')return send(res,202,start(doc,voice));if(sub==='cancel'&&req.method==='POST')return send(res,200,cancel(doc,voice));return send(res,404,{error:'Unknown narration route.'});}catch(e){return send(res,e.status||500,{error:e.message||'Narration unavailable.'});}}
module.exports={route,status,start,forget,pickLibrary,_test:{chunks,speechText,wave,joinWaves,descriptor}};



